// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {api} from '../models';

export function CreateCase(arg1:string,arg2:string,arg3:Array<db.Rule>):Promise<db.TestCase>;

export function CreateSuite(arg1:string,arg2:string):Promise<db.TestSuite>;

export function DeleteCase(arg1:string):Promise<void>;

export function DeleteSuite(arg1:string):Promise<void>;

export function GetAPIURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetRun(arg1:string):Promise<api.RunResult>;

export function GetSuite(arg1:string):Promise<db.TestSuite>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListCases(arg1:string):Promise<Array<db.TestCase>>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function ListRuns(arg1:string):Promise<Array<db.TestRun>>;

export function ListSuites():Promise<Array<db.TestSuite>>;

export function Quit():Promise<void>;

export function RevokeKey(arg1:string):Promise<void>;

export function RunSuite(arg1:string,arg2:string,arg3:Array<api.RunCaseInput>):Promise<api.RunResult>;
