// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCase(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCase'](arg1, arg2, arg3);
}

export function CreateSuite(arg1, arg2) {
  return window['go']['main']['App']['CreateSuite'](arg1, arg2);
}

export function DeleteCase(arg1) {
  return window['go']['main']['App']['DeleteCase'](arg1);
}

export function DeleteSuite(arg1) {
  return window['go']['main']['App']['DeleteSuite'](arg1);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetRun(arg1) {
  return window['go']['main']['App']['GetRun'](arg1);
}

export function GetSuite(arg1) {
  return window['go']['main']['App']['GetSuite'](arg1);
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListCases(arg1) {
  return window['go']['main']['App']['ListCases'](arg1);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListRuns(arg1) {
  return window['go']['main']['App']['ListRuns'](arg1);
}

export function ListSuites() {
  return window['go']['main']['App']['ListSuites']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function RunSuite(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunSuite'](arg1, arg2, arg3);
}
